### PR TITLE
Managed empty input to reset items

### PR DESCRIPTION
**Pull request by pascalheraud**
Call to updateItems is not done when field is empty (for instance if we remove selection using backspace). I changed utils to do the call even if field is empty, thus upadateItems callback can empty items

### CODE REVIEW

**Comment by pascalheraud** [comment]
@Flaburgan  or @mat-chartier can you review and merge this ?

**Comment by Flaburgan** [comment]
Why does it change that many files, did you rebase on a more recent version or anything?

**Comment by pascalheraud** [comment]
docs/ : it's normal since I rebuilt the package and id changed
src/utils.js : it's my fix
dist/v-autocomplete.js : it's the dist package

So for me it's normal

**Comment by pascalheraud** [comment]
I forgot to commit files after rebuild. A lot of files are changed but I don't know exactly why. It's JS magic.... :)

**Pull request merged**
